services:
  fastapi_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5444:5432"

  fastapi_app:
    image: fastapi_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - fastapi_database
    environment:
      DATABASE_URL: "postgresql+psycopg://app_user:app_password@fastapi_database:5432/app_db"

volumes:
  pgdata:
